### ISSUE TITLE
Better OAuth error checking/reporting

### ISSUE THREAD

**Issue by joehobson** [navnorth/LRphpLib#2]
I'm trying to get publishing with OAuth working and I run into this error:

> Notice: Undefined variable: res in /Users/joehobson/Documents/navNorth/OET/LearningReg/src/LRphpLib/LearningRegistry/src/Http/LearningRegistryHTTPClient.php on line 57
> Fatal error: Call to a member function getStatusCode() on a non-object in /Users/joehobson/Documents/navNorth/OET/LearningReg/src/LRphpLib/LearningRegistry/src/Http/LearningRegistryHTTPClient.php on line 57

in my config, for oauthSignature, I'm pulling the values from https://sandbox.learningregistry.org/apps/oauth-key-management/ -- but i didn't know whether to use oauth_token_secret or oauth_consumer_secret. Then I figured out that you concatenate the two and it worked.

Would be nice if we could check the OAuth handshake or return some other error if the oauthSignature is wrong.

**Comment by pgogy** [comment]
Should be fixed in the latest commit
